/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c4a21c77-794b-43ea-932b-bb853f7c161b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L9bpcDjoo",
    "aws_user_pools_web_client_id": "144f975vs82psmeh7enaohm8br",
    "oauth": {
        "domain": "iynnpnhmjppr-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://idcwwe10dbcd6b-10dbcd6b-staging.auth.us-east-1.amazoncognito.com/oath2/idresponse",
        "redirectSignOut": "https://idcwwe10dbcd6b-10dbcd6b-staging.auth.us-east-1.amazoncognito.com/oath2/idresponse",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
